name: canteco_app
description: University project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  water_drop_nav_bar: ^2.2.0+4

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  #image
  flutter_svg: ^1.1.6


flutter:
  uses-material-design: true
  assets:
      - assets/images/

  # fonts:
  #   - family: inter
  #     fonts:
  #       - asset: fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: fonts/Inter-Regular.ttf
  #         weight: 500