name: canteco_app
description: University project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.2
  email_validator: ^2.0.1
  smooth_page_indicator: ^1.0.0+2
  image_picker: ^0.8.6
  flutter_svg: ^1.1.6
  charts_flutter:
  http: ^0.13.4
  http_interceptor: ^1.0.2
  path_provider: ^2.0.11
  confetti: ^0.7.0
  sticky_headers: ^0.3.0+2
  shared_preferences: ^2.0.15
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0

  #image

  
  flutter_native_splash: ^2.2.16

flutter_native_splash: 
  color: "#ffffff"
  image: "assets/images/logoP.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
      - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon_logo.png"

  # fonts:
  #   - family: inter
  #     fonts:
  #       - asset: fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: fonts/Inter-Regular.ttf
  #         weight: 500